### ISSUE TITLE
Spurious errors 2: issue with -e abrupt4xCO2

### ISSUE THREAD

**Issue by chloemackallah** [cmip6dr/dreqPy#24]
When I attempt to pull a request for the abrupt4xCO2 experiment (e.g. drq -m CMIP -t 1 -p 1 --printVars --printLinesMax 20 -e abrupt4xCO2 --xls), I get the error:

Traceback (most recent call last):
  File "/home/mac570/.local/bin/drq", line 11, in <module>
    sys.exit(main_entry())
  File "/home/mac570/.local/lib/python2.7/site-packages/dreqPy/dreqCmdl.py", line 53, in main_entry
    x.run()
  File "/home/mac570/.local/lib/python2.7/site-packages/dreqPy/scope.py", line 1900, in run
    if ttm[1] > 0 and tte[1] == 0 or (ttm[2][0][0] > 0.6*tte[2][0][0]):
IndexError: tuple index out of range

I seem to only get this for the abrupt4xCO2 experiment, and no others as far as I can tell.

**Comment by martinjuckes** [comment]
@chloemackallah : this is an error in some code which is trying to provide helpful hints about the experiment name when you have entered an invalid name. The simple way to avoid this is to use `abrupt-4xCO2`, which is the correct name.

The bug is in the logical expression, which should be bracketed:
` if ttm[1] > 0 and **(**tte[1] == 0 or (ttm[2][0][0] > 0.6*tte[2][0][0])**)**:`
I'll patch this.
With this patch in place, your command will produce:
`NOT FOUND: abrupt4xCO2:  SUGGESTIONS: abrupt-4xCO2 [ 1.0]; abrupt-2xCO2 [ 0.9]; abrupt-4xCO2 [ 0.9]; abrupt-0p5xCO2 [ 0.8]; abrupt-2xCO2 [ 0.8]; abrupt-0p5xCO2 [ 0.7]`
followed by an exception.

There is a secondary problem here, in that some suggestions are listed twice. But the correct option does come top of the list.

**Comment by martinjuckes** [comment]
Duplicate listing of suggestions was double counting in the matching method ... now fixed.
